//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AI_Forge_Web_App.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/AI_Forge_Service")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AI_Forge_Web_App.ServiceReference.Invoice_Line[] Invoice_LinesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PROD_CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PROD_DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PROD_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PROD_Image_PathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short PROD_InventoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PROD_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PROD_PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SLE_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AI_Forge_Web_App.ServiceReference.Sale SaleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AI_Forge_Web_App.ServiceReference.Invoice_Line[] Invoice_Lines {
            get {
                return this.Invoice_LinesField;
            }
            set {
                if ((object.ReferenceEquals(this.Invoice_LinesField, value) != true)) {
                    this.Invoice_LinesField = value;
                    this.RaisePropertyChanged("Invoice_Lines");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PROD_Category {
            get {
                return this.PROD_CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.PROD_CategoryField, value) != true)) {
                    this.PROD_CategoryField = value;
                    this.RaisePropertyChanged("PROD_Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PROD_Description {
            get {
                return this.PROD_DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.PROD_DescriptionField, value) != true)) {
                    this.PROD_DescriptionField = value;
                    this.RaisePropertyChanged("PROD_Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PROD_ID {
            get {
                return this.PROD_IDField;
            }
            set {
                if ((this.PROD_IDField.Equals(value) != true)) {
                    this.PROD_IDField = value;
                    this.RaisePropertyChanged("PROD_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PROD_Image_Path {
            get {
                return this.PROD_Image_PathField;
            }
            set {
                if ((object.ReferenceEquals(this.PROD_Image_PathField, value) != true)) {
                    this.PROD_Image_PathField = value;
                    this.RaisePropertyChanged("PROD_Image_Path");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short PROD_Inventory {
            get {
                return this.PROD_InventoryField;
            }
            set {
                if ((this.PROD_InventoryField.Equals(value) != true)) {
                    this.PROD_InventoryField = value;
                    this.RaisePropertyChanged("PROD_Inventory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PROD_Name {
            get {
                return this.PROD_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.PROD_NameField, value) != true)) {
                    this.PROD_NameField = value;
                    this.RaisePropertyChanged("PROD_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PROD_Price {
            get {
                return this.PROD_PriceField;
            }
            set {
                if ((this.PROD_PriceField.Equals(value) != true)) {
                    this.PROD_PriceField = value;
                    this.RaisePropertyChanged("PROD_Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SLE_ID {
            get {
                return this.SLE_IDField;
            }
            set {
                if ((this.SLE_IDField.Equals(value) != true)) {
                    this.SLE_IDField = value;
                    this.RaisePropertyChanged("SLE_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AI_Forge_Web_App.ServiceReference.Sale Sale {
            get {
                return this.SaleField;
            }
            set {
                if ((object.ReferenceEquals(this.SaleField, value) != true)) {
                    this.SaleField = value;
                    this.RaisePropertyChanged("Sale");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sale", Namespace="http://schemas.datacontract.org/2004/07/AI_Forge_Service")]
    [System.SerializableAttribute()]
    public partial class Sale : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AI_Forge_Web_App.ServiceReference.Product[] ProductsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SLE_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SLE_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte SLE_ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AI_Forge_Web_App.ServiceReference.Product[] Products {
            get {
                return this.ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductsField, value) != true)) {
                    this.ProductsField = value;
                    this.RaisePropertyChanged("Products");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SLE_ID {
            get {
                return this.SLE_IDField;
            }
            set {
                if ((this.SLE_IDField.Equals(value) != true)) {
                    this.SLE_IDField = value;
                    this.RaisePropertyChanged("SLE_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SLE_Name {
            get {
                return this.SLE_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.SLE_NameField, value) != true)) {
                    this.SLE_NameField = value;
                    this.RaisePropertyChanged("SLE_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte SLE_Value {
            get {
                return this.SLE_ValueField;
            }
            set {
                if ((this.SLE_ValueField.Equals(value) != true)) {
                    this.SLE_ValueField = value;
                    this.RaisePropertyChanged("SLE_Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Invoice_Line", Namespace="http://schemas.datacontract.org/2004/07/AI_Forge_Service")]
    [System.SerializableAttribute()]
    public partial class Invoice_Line : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AI_Forge_Web_App.ServiceReference.Invoice InvoiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InvoiceL_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal InvoiceL_Price_EachField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short InvoiceL_QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Invoice_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PROD_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AI_Forge_Web_App.ServiceReference.Product ProductField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AI_Forge_Web_App.ServiceReference.Invoice Invoice {
            get {
                return this.InvoiceField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceField, value) != true)) {
                    this.InvoiceField = value;
                    this.RaisePropertyChanged("Invoice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InvoiceL_Id {
            get {
                return this.InvoiceL_IdField;
            }
            set {
                if ((this.InvoiceL_IdField.Equals(value) != true)) {
                    this.InvoiceL_IdField = value;
                    this.RaisePropertyChanged("InvoiceL_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal InvoiceL_Price_Each {
            get {
                return this.InvoiceL_Price_EachField;
            }
            set {
                if ((this.InvoiceL_Price_EachField.Equals(value) != true)) {
                    this.InvoiceL_Price_EachField = value;
                    this.RaisePropertyChanged("InvoiceL_Price_Each");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short InvoiceL_Quantity {
            get {
                return this.InvoiceL_QuantityField;
            }
            set {
                if ((this.InvoiceL_QuantityField.Equals(value) != true)) {
                    this.InvoiceL_QuantityField = value;
                    this.RaisePropertyChanged("InvoiceL_Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Invoice_Id {
            get {
                return this.Invoice_IdField;
            }
            set {
                if ((this.Invoice_IdField.Equals(value) != true)) {
                    this.Invoice_IdField = value;
                    this.RaisePropertyChanged("Invoice_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PROD_Id {
            get {
                return this.PROD_IdField;
            }
            set {
                if ((this.PROD_IdField.Equals(value) != true)) {
                    this.PROD_IdField = value;
                    this.RaisePropertyChanged("PROD_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AI_Forge_Web_App.ServiceReference.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Invoice", Namespace="http://schemas.datacontract.org/2004/07/AI_Forge_Service")]
    [System.SerializableAttribute()]
    public partial class Invoice : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Invoice_DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Invoice_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AI_Forge_Web_App.ServiceReference.Invoice_Line[] Invoice_LinesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AI_Forge_Web_App.ServiceReference.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> VCHR_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AI_Forge_Web_App.ServiceReference.Voucher VoucherField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Invoice_Date {
            get {
                return this.Invoice_DateField;
            }
            set {
                if ((this.Invoice_DateField.Equals(value) != true)) {
                    this.Invoice_DateField = value;
                    this.RaisePropertyChanged("Invoice_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Invoice_Id {
            get {
                return this.Invoice_IdField;
            }
            set {
                if ((this.Invoice_IdField.Equals(value) != true)) {
                    this.Invoice_IdField = value;
                    this.RaisePropertyChanged("Invoice_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AI_Forge_Web_App.ServiceReference.Invoice_Line[] Invoice_Lines {
            get {
                return this.Invoice_LinesField;
            }
            set {
                if ((object.ReferenceEquals(this.Invoice_LinesField, value) != true)) {
                    this.Invoice_LinesField = value;
                    this.RaisePropertyChanged("Invoice_Lines");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AI_Forge_Web_App.ServiceReference.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_Id {
            get {
                return this.User_IdField;
            }
            set {
                if ((this.User_IdField.Equals(value) != true)) {
                    this.User_IdField = value;
                    this.RaisePropertyChanged("User_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> VCHR_ID {
            get {
                return this.VCHR_IDField;
            }
            set {
                if ((this.VCHR_IDField.Equals(value) != true)) {
                    this.VCHR_IDField = value;
                    this.RaisePropertyChanged("VCHR_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AI_Forge_Web_App.ServiceReference.Voucher Voucher {
            get {
                return this.VoucherField;
            }
            set {
                if ((object.ReferenceEquals(this.VoucherField, value) != true)) {
                    this.VoucherField = value;
                    this.RaisePropertyChanged("Voucher");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/AI_Forge_Service")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AI_Forge_Web_App.ServiceReference.Address_Book[] Address_BooksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Forge_PointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AI_Forge_Web_App.ServiceReference.Invoice[] InvoicesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_ContactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> User_DOBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char User_GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AI_Forge_Web_App.ServiceReference.Address_Book[] Address_Books {
            get {
                return this.Address_BooksField;
            }
            set {
                if ((object.ReferenceEquals(this.Address_BooksField, value) != true)) {
                    this.Address_BooksField = value;
                    this.RaisePropertyChanged("Address_Books");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Forge_Points {
            get {
                return this.Forge_PointsField;
            }
            set {
                if ((this.Forge_PointsField.Equals(value) != true)) {
                    this.Forge_PointsField = value;
                    this.RaisePropertyChanged("Forge_Points");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AI_Forge_Web_App.ServiceReference.Invoice[] Invoices {
            get {
                return this.InvoicesField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoicesField, value) != true)) {
                    this.InvoicesField = value;
                    this.RaisePropertyChanged("Invoices");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_Contact {
            get {
                return this.User_ContactField;
            }
            set {
                if ((object.ReferenceEquals(this.User_ContactField, value) != true)) {
                    this.User_ContactField = value;
                    this.RaisePropertyChanged("User_Contact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> User_DOB {
            get {
                return this.User_DOBField;
            }
            set {
                if ((this.User_DOBField.Equals(value) != true)) {
                    this.User_DOBField = value;
                    this.RaisePropertyChanged("User_DOB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_Email {
            get {
                return this.User_EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.User_EmailField, value) != true)) {
                    this.User_EmailField = value;
                    this.RaisePropertyChanged("User_Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char User_Gender {
            get {
                return this.User_GenderField;
            }
            set {
                if ((this.User_GenderField.Equals(value) != true)) {
                    this.User_GenderField = value;
                    this.RaisePropertyChanged("User_Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_Id {
            get {
                return this.User_IdField;
            }
            set {
                if ((this.User_IdField.Equals(value) != true)) {
                    this.User_IdField = value;
                    this.RaisePropertyChanged("User_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_Name {
            get {
                return this.User_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.User_NameField, value) != true)) {
                    this.User_NameField = value;
                    this.RaisePropertyChanged("User_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_Password {
            get {
                return this.User_PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.User_PasswordField, value) != true)) {
                    this.User_PasswordField = value;
                    this.RaisePropertyChanged("User_Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_Surname {
            get {
                return this.User_SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.User_SurnameField, value) != true)) {
                    this.User_SurnameField = value;
                    this.RaisePropertyChanged("User_Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_Type {
            get {
                return this.User_TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.User_TypeField, value) != true)) {
                    this.User_TypeField = value;
                    this.RaisePropertyChanged("User_Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Voucher", Namespace="http://schemas.datacontract.org/2004/07/AI_Forge_Service")]
    [System.SerializableAttribute()]
    public partial class Voucher : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AI_Forge_Web_App.ServiceReference.Invoice[] InvoicesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RedeemedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHR_CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VCHR_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VCHR_ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AI_Forge_Web_App.ServiceReference.Invoice[] Invoices {
            get {
                return this.InvoicesField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoicesField, value) != true)) {
                    this.InvoicesField = value;
                    this.RaisePropertyChanged("Invoices");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Redeemed {
            get {
                return this.RedeemedField;
            }
            set {
                if ((this.RedeemedField.Equals(value) != true)) {
                    this.RedeemedField = value;
                    this.RaisePropertyChanged("Redeemed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VCHR_Code {
            get {
                return this.VCHR_CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHR_CodeField, value) != true)) {
                    this.VCHR_CodeField = value;
                    this.RaisePropertyChanged("VCHR_Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VCHR_ID {
            get {
                return this.VCHR_IDField;
            }
            set {
                if ((this.VCHR_IDField.Equals(value) != true)) {
                    this.VCHR_IDField = value;
                    this.RaisePropertyChanged("VCHR_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VCHR_Value {
            get {
                return this.VCHR_ValueField;
            }
            set {
                if ((this.VCHR_ValueField.Equals(value) != true)) {
                    this.VCHR_ValueField = value;
                    this.RaisePropertyChanged("VCHR_Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address_Book", Namespace="http://schemas.datacontract.org/2004/07/AI_Forge_Service")]
    [System.SerializableAttribute()]
    public partial class Address_Book : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ADRS_DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ADRS_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AI_Forge_Web_App.ServiceReference.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ADRS_Details {
            get {
                return this.ADRS_DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.ADRS_DetailsField, value) != true)) {
                    this.ADRS_DetailsField = value;
                    this.RaisePropertyChanged("ADRS_Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ADRS_ID {
            get {
                return this.ADRS_IDField;
            }
            set {
                if ((this.ADRS_IDField.Equals(value) != true)) {
                    this.ADRS_IDField = value;
                    this.RaisePropertyChanged("ADRS_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AI_Forge_Web_App.ServiceReference.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_Id {
            get {
                return this.User_IdField;
            }
            set {
                if ((this.User_IdField.Equals(value) != true)) {
                    this.User_IdField = value;
                    this.RaisePropertyChanged("User_Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IAI_Forge_Service")]
    public interface IAI_Forge_Service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/GetProducts", ReplyAction="http://tempuri.org/IAI_Forge_Service/GetProductsResponse")]
        AI_Forge_Web_App.ServiceReference.Product[] GetProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/GetProducts", ReplyAction="http://tempuri.org/IAI_Forge_Service/GetProductsResponse")]
        System.Threading.Tasks.Task<AI_Forge_Web_App.ServiceReference.Product[]> GetProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/GetProduct", ReplyAction="http://tempuri.org/IAI_Forge_Service/GetProductResponse")]
        AI_Forge_Web_App.ServiceReference.Product GetProduct(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/GetProduct", ReplyAction="http://tempuri.org/IAI_Forge_Service/GetProductResponse")]
        System.Threading.Tasks.Task<AI_Forge_Web_App.ServiceReference.Product> GetProductAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/IncreaseInventoryBy", ReplyAction="http://tempuri.org/IAI_Forge_Service/IncreaseInventoryByResponse")]
        bool IncreaseInventoryBy(int prod_ID, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/IncreaseInventoryBy", ReplyAction="http://tempuri.org/IAI_Forge_Service/IncreaseInventoryByResponse")]
        System.Threading.Tasks.Task<bool> IncreaseInventoryByAsync(int prod_ID, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/GetInventoryOf", ReplyAction="http://tempuri.org/IAI_Forge_Service/GetInventoryOfResponse")]
        int GetInventoryOf(int prod_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/GetInventoryOf", ReplyAction="http://tempuri.org/IAI_Forge_Service/GetInventoryOfResponse")]
        System.Threading.Tasks.Task<int> GetInventoryOfAsync(int prod_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/GetProductsOnSpecial", ReplyAction="http://tempuri.org/IAI_Forge_Service/GetProductsOnSpecialResponse")]
        AI_Forge_Web_App.ServiceReference.Product[] GetProductsOnSpecial();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/GetProductsOnSpecial", ReplyAction="http://tempuri.org/IAI_Forge_Service/GetProductsOnSpecialResponse")]
        System.Threading.Tasks.Task<AI_Forge_Web_App.ServiceReference.Product[]> GetProductsOnSpecialAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/GetSale", ReplyAction="http://tempuri.org/IAI_Forge_Service/GetSaleResponse")]
        AI_Forge_Web_App.ServiceReference.Sale GetSale(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/GetSale", ReplyAction="http://tempuri.org/IAI_Forge_Service/GetSaleResponse")]
        System.Threading.Tasks.Task<AI_Forge_Web_App.ServiceReference.Sale> GetSaleAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/GetCatagories", ReplyAction="http://tempuri.org/IAI_Forge_Service/GetCatagoriesResponse")]
        string[] GetCatagories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/GetCatagories", ReplyAction="http://tempuri.org/IAI_Forge_Service/GetCatagoriesResponse")]
        System.Threading.Tasks.Task<string[]> GetCatagoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/Login", ReplyAction="http://tempuri.org/IAI_Forge_Service/LoginResponse")]
        AI_Forge_Web_App.ServiceReference.User Login(string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/Login", ReplyAction="http://tempuri.org/IAI_Forge_Service/LoginResponse")]
        System.Threading.Tasks.Task<AI_Forge_Web_App.ServiceReference.User> LoginAsync(string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/Register", ReplyAction="http://tempuri.org/IAI_Forge_Service/RegisterResponse")]
        bool Register(string Name, string Surname, string Email, string Contact, char Gender, System.DateTime dob, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/Register", ReplyAction="http://tempuri.org/IAI_Forge_Service/RegisterResponse")]
        System.Threading.Tasks.Task<bool> RegisterAsync(string Name, string Surname, string Email, string Contact, char Gender, System.DateTime dob, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/UpdatePersonalDetails", ReplyAction="http://tempuri.org/IAI_Forge_Service/UpdatePersonalDetailsResponse")]
        bool UpdatePersonalDetails(int id, string Name, string Surname, string Email, string Contact, char Gender, System.DateTime dob);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/UpdatePersonalDetails", ReplyAction="http://tempuri.org/IAI_Forge_Service/UpdatePersonalDetailsResponse")]
        System.Threading.Tasks.Task<bool> UpdatePersonalDetailsAsync(int id, string Name, string Surname, string Email, string Contact, char Gender, System.DateTime dob);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/ChangePassword", ReplyAction="http://tempuri.org/IAI_Forge_Service/ChangePasswordResponse")]
        bool ChangePassword(int id, string oldPassword, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/ChangePassword", ReplyAction="http://tempuri.org/IAI_Forge_Service/ChangePasswordResponse")]
        System.Threading.Tasks.Task<bool> ChangePasswordAsync(int id, string oldPassword, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/AddAddress", ReplyAction="http://tempuri.org/IAI_Forge_Service/AddAddressResponse")]
        bool AddAddress(int user_id, string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/AddAddress", ReplyAction="http://tempuri.org/IAI_Forge_Service/AddAddressResponse")]
        System.Threading.Tasks.Task<bool> AddAddressAsync(int user_id, string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/GetAddress", ReplyAction="http://tempuri.org/IAI_Forge_Service/GetAddressResponse")]
        AI_Forge_Web_App.ServiceReference.Address_Book GetAddress(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/GetAddress", ReplyAction="http://tempuri.org/IAI_Forge_Service/GetAddressResponse")]
        System.Threading.Tasks.Task<AI_Forge_Web_App.ServiceReference.Address_Book> GetAddressAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/UpdateAddress", ReplyAction="http://tempuri.org/IAI_Forge_Service/UpdateAddressResponse")]
        bool UpdateAddress(int id, string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/UpdateAddress", ReplyAction="http://tempuri.org/IAI_Forge_Service/UpdateAddressResponse")]
        System.Threading.Tasks.Task<bool> UpdateAddressAsync(int id, string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/RemoveAddress", ReplyAction="http://tempuri.org/IAI_Forge_Service/RemoveAddressResponse")]
        bool RemoveAddress(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/RemoveAddress", ReplyAction="http://tempuri.org/IAI_Forge_Service/RemoveAddressResponse")]
        System.Threading.Tasks.Task<bool> RemoveAddressAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/UpdateProduct", ReplyAction="http://tempuri.org/IAI_Forge_Service/UpdateProductResponse")]
        bool UpdateProduct(int id, string name, int price, string imgPath, string description, string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/UpdateProduct", ReplyAction="http://tempuri.org/IAI_Forge_Service/UpdateProductResponse")]
        System.Threading.Tasks.Task<bool> UpdateProductAsync(int id, string name, int price, string imgPath, string description, string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/GetUser", ReplyAction="http://tempuri.org/IAI_Forge_Service/GetUserResponse")]
        AI_Forge_Web_App.ServiceReference.User GetUser(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/GetUser", ReplyAction="http://tempuri.org/IAI_Forge_Service/GetUserResponse")]
        System.Threading.Tasks.Task<AI_Forge_Web_App.ServiceReference.User> GetUserAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/VerifyEmail", ReplyAction="http://tempuri.org/IAI_Forge_Service/VerifyEmailResponse")]
        AI_Forge_Web_App.ServiceReference.User VerifyEmail(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/VerifyEmail", ReplyAction="http://tempuri.org/IAI_Forge_Service/VerifyEmailResponse")]
        System.Threading.Tasks.Task<AI_Forge_Web_App.ServiceReference.User> VerifyEmailAsync(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/AddProduct", ReplyAction="http://tempuri.org/IAI_Forge_Service/AddProductResponse")]
        bool AddProduct(string name, int price, string imgPath, string description, string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/AddProduct", ReplyAction="http://tempuri.org/IAI_Forge_Service/AddProductResponse")]
        System.Threading.Tasks.Task<bool> AddProductAsync(string name, int price, string imgPath, string description, string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/DeleteProduct", ReplyAction="http://tempuri.org/IAI_Forge_Service/DeleteProductResponse")]
        bool DeleteProduct(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/DeleteProduct", ReplyAction="http://tempuri.org/IAI_Forge_Service/DeleteProductResponse")]
        System.Threading.Tasks.Task<bool> DeleteProductAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/Transact", ReplyAction="http://tempuri.org/IAI_Forge_Service/TransactResponse")]
        bool Transact(int id, int vchr_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/Transact", ReplyAction="http://tempuri.org/IAI_Forge_Service/TransactResponse")]
        System.Threading.Tasks.Task<bool> TransactAsync(int id, int vchr_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/AddToInvoice", ReplyAction="http://tempuri.org/IAI_Forge_Service/AddToInvoiceResponse")]
        bool AddToInvoice(int id, int prod_id, decimal price, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/AddToInvoice", ReplyAction="http://tempuri.org/IAI_Forge_Service/AddToInvoiceResponse")]
        System.Threading.Tasks.Task<bool> AddToInvoiceAsync(int id, int prod_id, decimal price, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/CreateInvoice", ReplyAction="http://tempuri.org/IAI_Forge_Service/CreateInvoiceResponse")]
        int CreateInvoice(int user_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/CreateInvoice", ReplyAction="http://tempuri.org/IAI_Forge_Service/CreateInvoiceResponse")]
        System.Threading.Tasks.Task<int> CreateInvoiceAsync(int user_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/GetInvoice", ReplyAction="http://tempuri.org/IAI_Forge_Service/GetInvoiceResponse")]
        AI_Forge_Web_App.ServiceReference.Invoice GetInvoice(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/GetInvoice", ReplyAction="http://tempuri.org/IAI_Forge_Service/GetInvoiceResponse")]
        System.Threading.Tasks.Task<AI_Forge_Web_App.ServiceReference.Invoice> GetInvoiceAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/GetInvoiceSummary", ReplyAction="http://tempuri.org/IAI_Forge_Service/GetInvoiceSummaryResponse")]
        double[] GetInvoiceSummary(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/GetInvoiceSummary", ReplyAction="http://tempuri.org/IAI_Forge_Service/GetInvoiceSummaryResponse")]
        System.Threading.Tasks.Task<double[]> GetInvoiceSummaryAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/AddVoucher", ReplyAction="http://tempuri.org/IAI_Forge_Service/AddVoucherResponse")]
        bool AddVoucher(int value, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_Service/AddVoucher", ReplyAction="http://tempuri.org/IAI_Forge_Service/AddVoucherResponse")]
        System.Threading.Tasks.Task<bool> AddVoucherAsync(int value, string code);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAI_Forge_ServiceChannel : AI_Forge_Web_App.ServiceReference.IAI_Forge_Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AI_Forge_ServiceClient : System.ServiceModel.ClientBase<AI_Forge_Web_App.ServiceReference.IAI_Forge_Service>, AI_Forge_Web_App.ServiceReference.IAI_Forge_Service {
        
        public AI_Forge_ServiceClient() {
        }
        
        public AI_Forge_ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AI_Forge_ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AI_Forge_ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AI_Forge_ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AI_Forge_Web_App.ServiceReference.Product[] GetProducts() {
            return base.Channel.GetProducts();
        }
        
        public System.Threading.Tasks.Task<AI_Forge_Web_App.ServiceReference.Product[]> GetProductsAsync() {
            return base.Channel.GetProductsAsync();
        }
        
        public AI_Forge_Web_App.ServiceReference.Product GetProduct(int id) {
            return base.Channel.GetProduct(id);
        }
        
        public System.Threading.Tasks.Task<AI_Forge_Web_App.ServiceReference.Product> GetProductAsync(int id) {
            return base.Channel.GetProductAsync(id);
        }
        
        public bool IncreaseInventoryBy(int prod_ID, int quantity) {
            return base.Channel.IncreaseInventoryBy(prod_ID, quantity);
        }
        
        public System.Threading.Tasks.Task<bool> IncreaseInventoryByAsync(int prod_ID, int quantity) {
            return base.Channel.IncreaseInventoryByAsync(prod_ID, quantity);
        }
        
        public int GetInventoryOf(int prod_ID) {
            return base.Channel.GetInventoryOf(prod_ID);
        }
        
        public System.Threading.Tasks.Task<int> GetInventoryOfAsync(int prod_ID) {
            return base.Channel.GetInventoryOfAsync(prod_ID);
        }
        
        public AI_Forge_Web_App.ServiceReference.Product[] GetProductsOnSpecial() {
            return base.Channel.GetProductsOnSpecial();
        }
        
        public System.Threading.Tasks.Task<AI_Forge_Web_App.ServiceReference.Product[]> GetProductsOnSpecialAsync() {
            return base.Channel.GetProductsOnSpecialAsync();
        }
        
        public AI_Forge_Web_App.ServiceReference.Sale GetSale(int id) {
            return base.Channel.GetSale(id);
        }
        
        public System.Threading.Tasks.Task<AI_Forge_Web_App.ServiceReference.Sale> GetSaleAsync(int id) {
            return base.Channel.GetSaleAsync(id);
        }
        
        public string[] GetCatagories() {
            return base.Channel.GetCatagories();
        }
        
        public System.Threading.Tasks.Task<string[]> GetCatagoriesAsync() {
            return base.Channel.GetCatagoriesAsync();
        }
        
        public AI_Forge_Web_App.ServiceReference.User Login(string Email, string Password) {
            return base.Channel.Login(Email, Password);
        }
        
        public System.Threading.Tasks.Task<AI_Forge_Web_App.ServiceReference.User> LoginAsync(string Email, string Password) {
            return base.Channel.LoginAsync(Email, Password);
        }
        
        public bool Register(string Name, string Surname, string Email, string Contact, char Gender, System.DateTime dob, string Password) {
            return base.Channel.Register(Name, Surname, Email, Contact, Gender, dob, Password);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterAsync(string Name, string Surname, string Email, string Contact, char Gender, System.DateTime dob, string Password) {
            return base.Channel.RegisterAsync(Name, Surname, Email, Contact, Gender, dob, Password);
        }
        
        public bool UpdatePersonalDetails(int id, string Name, string Surname, string Email, string Contact, char Gender, System.DateTime dob) {
            return base.Channel.UpdatePersonalDetails(id, Name, Surname, Email, Contact, Gender, dob);
        }
        
        public System.Threading.Tasks.Task<bool> UpdatePersonalDetailsAsync(int id, string Name, string Surname, string Email, string Contact, char Gender, System.DateTime dob) {
            return base.Channel.UpdatePersonalDetailsAsync(id, Name, Surname, Email, Contact, Gender, dob);
        }
        
        public bool ChangePassword(int id, string oldPassword, string newPassword) {
            return base.Channel.ChangePassword(id, oldPassword, newPassword);
        }
        
        public System.Threading.Tasks.Task<bool> ChangePasswordAsync(int id, string oldPassword, string newPassword) {
            return base.Channel.ChangePasswordAsync(id, oldPassword, newPassword);
        }
        
        public bool AddAddress(int user_id, string address) {
            return base.Channel.AddAddress(user_id, address);
        }
        
        public System.Threading.Tasks.Task<bool> AddAddressAsync(int user_id, string address) {
            return base.Channel.AddAddressAsync(user_id, address);
        }
        
        public AI_Forge_Web_App.ServiceReference.Address_Book GetAddress(int id) {
            return base.Channel.GetAddress(id);
        }
        
        public System.Threading.Tasks.Task<AI_Forge_Web_App.ServiceReference.Address_Book> GetAddressAsync(int id) {
            return base.Channel.GetAddressAsync(id);
        }
        
        public bool UpdateAddress(int id, string address) {
            return base.Channel.UpdateAddress(id, address);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAddressAsync(int id, string address) {
            return base.Channel.UpdateAddressAsync(id, address);
        }
        
        public bool RemoveAddress(int id) {
            return base.Channel.RemoveAddress(id);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveAddressAsync(int id) {
            return base.Channel.RemoveAddressAsync(id);
        }
        
        public bool UpdateProduct(int id, string name, int price, string imgPath, string description, string category) {
            return base.Channel.UpdateProduct(id, name, price, imgPath, description, category);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateProductAsync(int id, string name, int price, string imgPath, string description, string category) {
            return base.Channel.UpdateProductAsync(id, name, price, imgPath, description, category);
        }
        
        public AI_Forge_Web_App.ServiceReference.User GetUser(int id) {
            return base.Channel.GetUser(id);
        }
        
        public System.Threading.Tasks.Task<AI_Forge_Web_App.ServiceReference.User> GetUserAsync(int id) {
            return base.Channel.GetUserAsync(id);
        }
        
        public AI_Forge_Web_App.ServiceReference.User VerifyEmail(string Email) {
            return base.Channel.VerifyEmail(Email);
        }
        
        public System.Threading.Tasks.Task<AI_Forge_Web_App.ServiceReference.User> VerifyEmailAsync(string Email) {
            return base.Channel.VerifyEmailAsync(Email);
        }
        
        public bool AddProduct(string name, int price, string imgPath, string description, string category) {
            return base.Channel.AddProduct(name, price, imgPath, description, category);
        }
        
        public System.Threading.Tasks.Task<bool> AddProductAsync(string name, int price, string imgPath, string description, string category) {
            return base.Channel.AddProductAsync(name, price, imgPath, description, category);
        }
        
        public bool DeleteProduct(int id) {
            return base.Channel.DeleteProduct(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteProductAsync(int id) {
            return base.Channel.DeleteProductAsync(id);
        }
        
        public bool Transact(int id, int vchr_id) {
            return base.Channel.Transact(id, vchr_id);
        }
        
        public System.Threading.Tasks.Task<bool> TransactAsync(int id, int vchr_id) {
            return base.Channel.TransactAsync(id, vchr_id);
        }
        
        public bool AddToInvoice(int id, int prod_id, decimal price, int quantity) {
            return base.Channel.AddToInvoice(id, prod_id, price, quantity);
        }
        
        public System.Threading.Tasks.Task<bool> AddToInvoiceAsync(int id, int prod_id, decimal price, int quantity) {
            return base.Channel.AddToInvoiceAsync(id, prod_id, price, quantity);
        }
        
        public int CreateInvoice(int user_id) {
            return base.Channel.CreateInvoice(user_id);
        }
        
        public System.Threading.Tasks.Task<int> CreateInvoiceAsync(int user_id) {
            return base.Channel.CreateInvoiceAsync(user_id);
        }
        
        public AI_Forge_Web_App.ServiceReference.Invoice GetInvoice(int id) {
            return base.Channel.GetInvoice(id);
        }
        
        public System.Threading.Tasks.Task<AI_Forge_Web_App.ServiceReference.Invoice> GetInvoiceAsync(int id) {
            return base.Channel.GetInvoiceAsync(id);
        }
        
        public double[] GetInvoiceSummary(int id) {
            return base.Channel.GetInvoiceSummary(id);
        }
        
        public System.Threading.Tasks.Task<double[]> GetInvoiceSummaryAsync(int id) {
            return base.Channel.GetInvoiceSummaryAsync(id);
        }
        
        public bool AddVoucher(int value, string code) {
            return base.Channel.AddVoucher(value, code);
        }
        
        public System.Threading.Tasks.Task<bool> AddVoucherAsync(int value, string code) {
            return base.Channel.AddVoucherAsync(value, code);
        }
    }
}
