//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AI_Forge_Web_App.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/AI_Forge_Service")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AI_Forge_Web_App.ServiceReference.Invoice[] InvoicesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool User_ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_ContactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> User_DOBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char User_GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AI_Forge_Web_App.ServiceReference.Invoice[] Invoices {
            get {
                return this.InvoicesField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoicesField, value) != true)) {
                    this.InvoicesField = value;
                    this.RaisePropertyChanged("Invoices");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool User_Active {
            get {
                return this.User_ActiveField;
            }
            set {
                if ((this.User_ActiveField.Equals(value) != true)) {
                    this.User_ActiveField = value;
                    this.RaisePropertyChanged("User_Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_Address {
            get {
                return this.User_AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.User_AddressField, value) != true)) {
                    this.User_AddressField = value;
                    this.RaisePropertyChanged("User_Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_Contact {
            get {
                return this.User_ContactField;
            }
            set {
                if ((object.ReferenceEquals(this.User_ContactField, value) != true)) {
                    this.User_ContactField = value;
                    this.RaisePropertyChanged("User_Contact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> User_DOB {
            get {
                return this.User_DOBField;
            }
            set {
                if ((this.User_DOBField.Equals(value) != true)) {
                    this.User_DOBField = value;
                    this.RaisePropertyChanged("User_DOB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_Email {
            get {
                return this.User_EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.User_EmailField, value) != true)) {
                    this.User_EmailField = value;
                    this.RaisePropertyChanged("User_Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char User_Gender {
            get {
                return this.User_GenderField;
            }
            set {
                if ((this.User_GenderField.Equals(value) != true)) {
                    this.User_GenderField = value;
                    this.RaisePropertyChanged("User_Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_Id {
            get {
                return this.User_IdField;
            }
            set {
                if ((this.User_IdField.Equals(value) != true)) {
                    this.User_IdField = value;
                    this.RaisePropertyChanged("User_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_Name {
            get {
                return this.User_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.User_NameField, value) != true)) {
                    this.User_NameField = value;
                    this.RaisePropertyChanged("User_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_Password {
            get {
                return this.User_PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.User_PasswordField, value) != true)) {
                    this.User_PasswordField = value;
                    this.RaisePropertyChanged("User_Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_Surname {
            get {
                return this.User_SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.User_SurnameField, value) != true)) {
                    this.User_SurnameField = value;
                    this.RaisePropertyChanged("User_Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_Type {
            get {
                return this.User_TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.User_TypeField, value) != true)) {
                    this.User_TypeField = value;
                    this.RaisePropertyChanged("User_Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Invoice", Namespace="http://schemas.datacontract.org/2004/07/AI_Forge_Service")]
    [System.SerializableAttribute()]
    public partial class Invoice : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Invoice_DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Invoice_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AI_Forge_Web_App.ServiceReference.Invoice_Line[] Invoice_LinesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AI_Forge_Web_App.ServiceReference.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Invoice_Date {
            get {
                return this.Invoice_DateField;
            }
            set {
                if ((this.Invoice_DateField.Equals(value) != true)) {
                    this.Invoice_DateField = value;
                    this.RaisePropertyChanged("Invoice_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Invoice_Id {
            get {
                return this.Invoice_IdField;
            }
            set {
                if ((this.Invoice_IdField.Equals(value) != true)) {
                    this.Invoice_IdField = value;
                    this.RaisePropertyChanged("Invoice_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AI_Forge_Web_App.ServiceReference.Invoice_Line[] Invoice_Lines {
            get {
                return this.Invoice_LinesField;
            }
            set {
                if ((object.ReferenceEquals(this.Invoice_LinesField, value) != true)) {
                    this.Invoice_LinesField = value;
                    this.RaisePropertyChanged("Invoice_Lines");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AI_Forge_Web_App.ServiceReference.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_Id {
            get {
                return this.User_IdField;
            }
            set {
                if ((this.User_IdField.Equals(value) != true)) {
                    this.User_IdField = value;
                    this.RaisePropertyChanged("User_Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Invoice_Line", Namespace="http://schemas.datacontract.org/2004/07/AI_Forge_Service")]
    [System.SerializableAttribute()]
    public partial class Invoice_Line : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AI_Forge_Web_App.ServiceReference.Invoice InvoiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InvoiceL_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal InvoiceL_PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InvoiceL_QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Invoice_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PROD_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AI_Forge_Web_App.ServiceReference.Product ProductField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AI_Forge_Web_App.ServiceReference.Invoice Invoice {
            get {
                return this.InvoiceField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceField, value) != true)) {
                    this.InvoiceField = value;
                    this.RaisePropertyChanged("Invoice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InvoiceL_Id {
            get {
                return this.InvoiceL_IdField;
            }
            set {
                if ((this.InvoiceL_IdField.Equals(value) != true)) {
                    this.InvoiceL_IdField = value;
                    this.RaisePropertyChanged("InvoiceL_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal InvoiceL_Price {
            get {
                return this.InvoiceL_PriceField;
            }
            set {
                if ((this.InvoiceL_PriceField.Equals(value) != true)) {
                    this.InvoiceL_PriceField = value;
                    this.RaisePropertyChanged("InvoiceL_Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InvoiceL_Quantity {
            get {
                return this.InvoiceL_QuantityField;
            }
            set {
                if ((this.InvoiceL_QuantityField.Equals(value) != true)) {
                    this.InvoiceL_QuantityField = value;
                    this.RaisePropertyChanged("InvoiceL_Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Invoice_Id {
            get {
                return this.Invoice_IdField;
            }
            set {
                if ((this.Invoice_IdField.Equals(value) != true)) {
                    this.Invoice_IdField = value;
                    this.RaisePropertyChanged("Invoice_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PROD_ID {
            get {
                return this.PROD_IDField;
            }
            set {
                if ((this.PROD_IDField.Equals(value) != true)) {
                    this.PROD_IDField = value;
                    this.RaisePropertyChanged("PROD_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AI_Forge_Web_App.ServiceReference.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/AI_Forge_Service")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AI_Forge_Web_App.ServiceReference.Invoice_Line[] Invoice_LinesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PROD_ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PROD_CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte PROD_DepthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PROD_DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte PROD_HeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PROD_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PROD_Image_PathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte PROD_InventoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PROD_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PROD_PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte PROD_WidthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SLE_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AI_Forge_Web_App.ServiceReference.Sale SaleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AI_Forge_Web_App.ServiceReference.Invoice_Line[] Invoice_Lines {
            get {
                return this.Invoice_LinesField;
            }
            set {
                if ((object.ReferenceEquals(this.Invoice_LinesField, value) != true)) {
                    this.Invoice_LinesField = value;
                    this.RaisePropertyChanged("Invoice_Lines");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PROD_Active {
            get {
                return this.PROD_ActiveField;
            }
            set {
                if ((this.PROD_ActiveField.Equals(value) != true)) {
                    this.PROD_ActiveField = value;
                    this.RaisePropertyChanged("PROD_Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PROD_Category {
            get {
                return this.PROD_CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.PROD_CategoryField, value) != true)) {
                    this.PROD_CategoryField = value;
                    this.RaisePropertyChanged("PROD_Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte PROD_Depth {
            get {
                return this.PROD_DepthField;
            }
            set {
                if ((this.PROD_DepthField.Equals(value) != true)) {
                    this.PROD_DepthField = value;
                    this.RaisePropertyChanged("PROD_Depth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PROD_Description {
            get {
                return this.PROD_DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.PROD_DescriptionField, value) != true)) {
                    this.PROD_DescriptionField = value;
                    this.RaisePropertyChanged("PROD_Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte PROD_Height {
            get {
                return this.PROD_HeightField;
            }
            set {
                if ((this.PROD_HeightField.Equals(value) != true)) {
                    this.PROD_HeightField = value;
                    this.RaisePropertyChanged("PROD_Height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PROD_ID {
            get {
                return this.PROD_IDField;
            }
            set {
                if ((this.PROD_IDField.Equals(value) != true)) {
                    this.PROD_IDField = value;
                    this.RaisePropertyChanged("PROD_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PROD_Image_Path {
            get {
                return this.PROD_Image_PathField;
            }
            set {
                if ((object.ReferenceEquals(this.PROD_Image_PathField, value) != true)) {
                    this.PROD_Image_PathField = value;
                    this.RaisePropertyChanged("PROD_Image_Path");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte PROD_Inventory {
            get {
                return this.PROD_InventoryField;
            }
            set {
                if ((this.PROD_InventoryField.Equals(value) != true)) {
                    this.PROD_InventoryField = value;
                    this.RaisePropertyChanged("PROD_Inventory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PROD_Name {
            get {
                return this.PROD_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.PROD_NameField, value) != true)) {
                    this.PROD_NameField = value;
                    this.RaisePropertyChanged("PROD_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PROD_Price {
            get {
                return this.PROD_PriceField;
            }
            set {
                if ((this.PROD_PriceField.Equals(value) != true)) {
                    this.PROD_PriceField = value;
                    this.RaisePropertyChanged("PROD_Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte PROD_Width {
            get {
                return this.PROD_WidthField;
            }
            set {
                if ((this.PROD_WidthField.Equals(value) != true)) {
                    this.PROD_WidthField = value;
                    this.RaisePropertyChanged("PROD_Width");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SLE_ID {
            get {
                return this.SLE_IDField;
            }
            set {
                if ((this.SLE_IDField.Equals(value) != true)) {
                    this.SLE_IDField = value;
                    this.RaisePropertyChanged("SLE_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AI_Forge_Web_App.ServiceReference.Sale Sale {
            get {
                return this.SaleField;
            }
            set {
                if ((object.ReferenceEquals(this.SaleField, value) != true)) {
                    this.SaleField = value;
                    this.RaisePropertyChanged("Sale");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sale", Namespace="http://schemas.datacontract.org/2004/07/AI_Forge_Service")]
    [System.SerializableAttribute()]
    public partial class Sale : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AI_Forge_Web_App.ServiceReference.Product[] ProductsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SLE_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SLE_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte SLE_ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AI_Forge_Web_App.ServiceReference.Product[] Products {
            get {
                return this.ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductsField, value) != true)) {
                    this.ProductsField = value;
                    this.RaisePropertyChanged("Products");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SLE_ID {
            get {
                return this.SLE_IDField;
            }
            set {
                if ((this.SLE_IDField.Equals(value) != true)) {
                    this.SLE_IDField = value;
                    this.RaisePropertyChanged("SLE_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SLE_Name {
            get {
                return this.SLE_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.SLE_NameField, value) != true)) {
                    this.SLE_NameField = value;
                    this.RaisePropertyChanged("SLE_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte SLE_Value {
            get {
                return this.SLE_ValueField;
            }
            set {
                if ((this.SLE_ValueField.Equals(value) != true)) {
                    this.SLE_ValueField = value;
                    this.RaisePropertyChanged("SLE_Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IAI_Forge_service")]
    public interface IAI_Forge_service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_service/Login", ReplyAction="http://tempuri.org/IAI_Forge_service/LoginResponse")]
        int Login(string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_service/Login", ReplyAction="http://tempuri.org/IAI_Forge_service/LoginResponse")]
        System.Threading.Tasks.Task<int> LoginAsync(string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_service/Register", ReplyAction="http://tempuri.org/IAI_Forge_service/RegisterResponse")]
        bool Register(string Name, string Surname, string Email, string Contact, char Gender, System.DateTime dob, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_service/Register", ReplyAction="http://tempuri.org/IAI_Forge_service/RegisterResponse")]
        System.Threading.Tasks.Task<bool> RegisterAsync(string Name, string Surname, string Email, string Contact, char Gender, System.DateTime dob, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_service/UpdateInfo", ReplyAction="http://tempuri.org/IAI_Forge_service/UpdateInfoResponse")]
        bool UpdateInfo(string Name, string Surname, string Email, string Contact, char Gender, System.DateTime dob, string Address, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_service/UpdateInfo", ReplyAction="http://tempuri.org/IAI_Forge_service/UpdateInfoResponse")]
        System.Threading.Tasks.Task<bool> UpdateInfoAsync(string Name, string Surname, string Email, string Contact, char Gender, System.DateTime dob, string Address, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_service/UpdateProduct", ReplyAction="http://tempuri.org/IAI_Forge_service/UpdateProductResponse")]
        bool UpdateProduct(int id, string name, int price, string category, int height, int width, int depth, string imgPath, string description, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_service/UpdateProduct", ReplyAction="http://tempuri.org/IAI_Forge_service/UpdateProductResponse")]
        System.Threading.Tasks.Task<bool> UpdateProductAsync(int id, string name, int price, string category, int height, int width, int depth, string imgPath, string description, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_service/GetUser", ReplyAction="http://tempuri.org/IAI_Forge_service/GetUserResponse")]
        AI_Forge_Web_App.ServiceReference.User GetUser(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_service/GetUser", ReplyAction="http://tempuri.org/IAI_Forge_service/GetUserResponse")]
        System.Threading.Tasks.Task<AI_Forge_Web_App.ServiceReference.User> GetUserAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_service/VerifyEmail", ReplyAction="http://tempuri.org/IAI_Forge_service/VerifyEmailResponse")]
        AI_Forge_Web_App.ServiceReference.User VerifyEmail(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_service/VerifyEmail", ReplyAction="http://tempuri.org/IAI_Forge_service/VerifyEmailResponse")]
        System.Threading.Tasks.Task<AI_Forge_Web_App.ServiceReference.User> VerifyEmailAsync(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_service/AddProduct", ReplyAction="http://tempuri.org/IAI_Forge_service/AddProductResponse")]
        bool AddProduct(string name, int price, string category, int height, int width, int depth, string imgPath, string description, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_service/AddProduct", ReplyAction="http://tempuri.org/IAI_Forge_service/AddProductResponse")]
        System.Threading.Tasks.Task<bool> AddProductAsync(string name, int price, string category, int height, int width, int depth, string imgPath, string description, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_service/DeleteProduct", ReplyAction="http://tempuri.org/IAI_Forge_service/DeleteProductResponse")]
        bool DeleteProduct(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_service/DeleteProduct", ReplyAction="http://tempuri.org/IAI_Forge_service/DeleteProductResponse")]
        System.Threading.Tasks.Task<bool> DeleteProductAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_service/GetProductsOnSpecial", ReplyAction="http://tempuri.org/IAI_Forge_service/GetProductsOnSpecialResponse")]
        AI_Forge_Web_App.ServiceReference.Product[] GetProductsOnSpecial();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_service/GetProductsOnSpecial", ReplyAction="http://tempuri.org/IAI_Forge_service/GetProductsOnSpecialResponse")]
        System.Threading.Tasks.Task<AI_Forge_Web_App.ServiceReference.Product[]> GetProductsOnSpecialAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_service/GetActiveProducts", ReplyAction="http://tempuri.org/IAI_Forge_service/GetActiveProductsResponse")]
        AI_Forge_Web_App.ServiceReference.Product[] GetActiveProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_service/GetActiveProducts", ReplyAction="http://tempuri.org/IAI_Forge_service/GetActiveProductsResponse")]
        System.Threading.Tasks.Task<AI_Forge_Web_App.ServiceReference.Product[]> GetActiveProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_service/GetProduct", ReplyAction="http://tempuri.org/IAI_Forge_service/GetProductResponse")]
        AI_Forge_Web_App.ServiceReference.Product GetProduct(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_service/GetProduct", ReplyAction="http://tempuri.org/IAI_Forge_service/GetProductResponse")]
        System.Threading.Tasks.Task<AI_Forge_Web_App.ServiceReference.Product> GetProductAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_service/GetSale", ReplyAction="http://tempuri.org/IAI_Forge_service/GetSaleResponse")]
        AI_Forge_Web_App.ServiceReference.Sale GetSale(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_service/GetSale", ReplyAction="http://tempuri.org/IAI_Forge_service/GetSaleResponse")]
        System.Threading.Tasks.Task<AI_Forge_Web_App.ServiceReference.Sale> GetSaleAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_service/GetProductCatagories", ReplyAction="http://tempuri.org/IAI_Forge_service/GetProductCatagoriesResponse")]
        string[] GetProductCatagories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAI_Forge_service/GetProductCatagories", ReplyAction="http://tempuri.org/IAI_Forge_service/GetProductCatagoriesResponse")]
        System.Threading.Tasks.Task<string[]> GetProductCatagoriesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAI_Forge_serviceChannel : AI_Forge_Web_App.ServiceReference.IAI_Forge_service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AI_Forge_serviceClient : System.ServiceModel.ClientBase<AI_Forge_Web_App.ServiceReference.IAI_Forge_service>, AI_Forge_Web_App.ServiceReference.IAI_Forge_service {
        
        public AI_Forge_serviceClient() {
        }
        
        public AI_Forge_serviceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AI_Forge_serviceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AI_Forge_serviceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AI_Forge_serviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Login(string Email, string Password) {
            return base.Channel.Login(Email, Password);
        }
        
        public System.Threading.Tasks.Task<int> LoginAsync(string Email, string Password) {
            return base.Channel.LoginAsync(Email, Password);
        }
        
        public bool Register(string Name, string Surname, string Email, string Contact, char Gender, System.DateTime dob, string Password) {
            return base.Channel.Register(Name, Surname, Email, Contact, Gender, dob, Password);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterAsync(string Name, string Surname, string Email, string Contact, char Gender, System.DateTime dob, string Password) {
            return base.Channel.RegisterAsync(Name, Surname, Email, Contact, Gender, dob, Password);
        }
        
        public bool UpdateInfo(string Name, string Surname, string Email, string Contact, char Gender, System.DateTime dob, string Address, string Password) {
            return base.Channel.UpdateInfo(Name, Surname, Email, Contact, Gender, dob, Address, Password);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateInfoAsync(string Name, string Surname, string Email, string Contact, char Gender, System.DateTime dob, string Address, string Password) {
            return base.Channel.UpdateInfoAsync(Name, Surname, Email, Contact, Gender, dob, Address, Password);
        }
        
        public bool UpdateProduct(int id, string name, int price, string category, int height, int width, int depth, string imgPath, string description, int quantity) {
            return base.Channel.UpdateProduct(id, name, price, category, height, width, depth, imgPath, description, quantity);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateProductAsync(int id, string name, int price, string category, int height, int width, int depth, string imgPath, string description, int quantity) {
            return base.Channel.UpdateProductAsync(id, name, price, category, height, width, depth, imgPath, description, quantity);
        }
        
        public AI_Forge_Web_App.ServiceReference.User GetUser(int id) {
            return base.Channel.GetUser(id);
        }
        
        public System.Threading.Tasks.Task<AI_Forge_Web_App.ServiceReference.User> GetUserAsync(int id) {
            return base.Channel.GetUserAsync(id);
        }
        
        public AI_Forge_Web_App.ServiceReference.User VerifyEmail(string Email) {
            return base.Channel.VerifyEmail(Email);
        }
        
        public System.Threading.Tasks.Task<AI_Forge_Web_App.ServiceReference.User> VerifyEmailAsync(string Email) {
            return base.Channel.VerifyEmailAsync(Email);
        }
        
        public bool AddProduct(string name, int price, string category, int height, int width, int depth, string imgPath, string description, int quantity) {
            return base.Channel.AddProduct(name, price, category, height, width, depth, imgPath, description, quantity);
        }
        
        public System.Threading.Tasks.Task<bool> AddProductAsync(string name, int price, string category, int height, int width, int depth, string imgPath, string description, int quantity) {
            return base.Channel.AddProductAsync(name, price, category, height, width, depth, imgPath, description, quantity);
        }
        
        public bool DeleteProduct(int id) {
            return base.Channel.DeleteProduct(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteProductAsync(int id) {
            return base.Channel.DeleteProductAsync(id);
        }
        
        public AI_Forge_Web_App.ServiceReference.Product[] GetProductsOnSpecial() {
            return base.Channel.GetProductsOnSpecial();
        }
        
        public System.Threading.Tasks.Task<AI_Forge_Web_App.ServiceReference.Product[]> GetProductsOnSpecialAsync() {
            return base.Channel.GetProductsOnSpecialAsync();
        }
        
        public AI_Forge_Web_App.ServiceReference.Product[] GetActiveProducts() {
            return base.Channel.GetActiveProducts();
        }
        
        public System.Threading.Tasks.Task<AI_Forge_Web_App.ServiceReference.Product[]> GetActiveProductsAsync() {
            return base.Channel.GetActiveProductsAsync();
        }
        
        public AI_Forge_Web_App.ServiceReference.Product GetProduct(int id) {
            return base.Channel.GetProduct(id);
        }
        
        public System.Threading.Tasks.Task<AI_Forge_Web_App.ServiceReference.Product> GetProductAsync(int id) {
            return base.Channel.GetProductAsync(id);
        }
        
        public AI_Forge_Web_App.ServiceReference.Sale GetSale(int id) {
            return base.Channel.GetSale(id);
        }
        
        public System.Threading.Tasks.Task<AI_Forge_Web_App.ServiceReference.Sale> GetSaleAsync(int id) {
            return base.Channel.GetSaleAsync(id);
        }
        
        public string[] GetProductCatagories() {
            return base.Channel.GetProductCatagories();
        }
        
        public System.Threading.Tasks.Task<string[]> GetProductCatagoriesAsync() {
            return base.Channel.GetProductCatagoriesAsync();
        }
    }
}
